name: Release WordPress Plugin
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install Yarn dependencies and build assets
        run: |
          cd app
          yarn install
          yarn build

      - name: Update index.php with new hash values
        run: |
          # Find the new JS and CSS files
          JS_FILE=$(ls app/dist/assets/index-*.js)
          CSS_FILE=$(ls app/dist/assets/index-*.css)

          # Extract just the filenames
          JS_FILENAME=$(basename $JS_FILE)
          CSS_FILENAME=$(basename $CSS_FILE)

          # Update the index.php file using sed
          sed -i "s@/app/dist/assets/index-[[:alnum:]]*.js@/app/dist/assets/${JS_FILENAME}@g" index.php
          sed -i "s@/app/dist/assets/index-[[:alnum:]]*.css@/app/dist/assets/${CSS_FILENAME}@g" index.php

      - name: Create plugin artifact
        run: |
          # Remove development files
          rm -rf app/node_modules/
          rm -rf .git/
          rm -f .gitignore

          # Create zip file (replace plugin-name with your plugin's name)
          zip -r altly-plugin.zip .

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: altly-plugin.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
